### ISSUE TITLE
Info about the extension?

### ISSUE THREAD

**Issue by SunPodder** [tldr-pages/tldr-neovim-extension#1]
What this extension is supposed to do?

I'm guessing it will be used to call tldr within neovim. Is there anyone working on this extension already? If not, let me know the idea.

![Screenshot_20230109-155041_Termux](https://user-images.githubusercontent.com/73415680/211281148-0e179c78-fa11-4c3d-8486-5af8e39c1ed8.jpg)
Will something like this work?

**Comment by kbdharun** [comment]
@SunPodder Thanks for this issue.

If I remember correctly, the previous maintainer who created this repo has left the project.

> Will something like this work?

Yeah, I too think it was something like this (to view cheatsheets quickly) along with tldr-lint. If you are interested in developing this extension please let me know, and I will invite you to this repo.

**Comment by SunPodder** [comment]
Hi there,
I'm definitely interested in contributing to this project. Please go ahead and invite me to the repo, and I'll get started on working on the extension.

**Comment by kbdharun** [comment]
Done, sent an invite.
